apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-boot-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          imagePullPolicy: IfNotPresent
          image: ngomansible/my_private_repo:56
          ports:
          - containerPort: 8085