apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myArgo_application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NgomSysOps/argo_cd_repo.git
    targetRevision: HEAD
    path: myFiles
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-app-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true